const data={
    products:[
        {
            _id:'1',
            name:'Nike slim shirt',
            category:'Slim shirts',
            image:'/images/image1.webp',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviws:12,
            description:'high quality product',
            CountInStock:10,
        },
        {
            _id:'2',
            name:'adidas',
            category:'sport shirts',
            image:'/images/image2.webp',
            price:120,
            brand:'adidas',
            rating:3,
            numReviws:12,
            description:'high quality product',
            CountInStock:10,
        },
        {
            _id:'3',
            name:'champions',
            category:' shirts',
            image:'/images/image3.jpg',
            price:120,
            brand:'champions',
            rating:2,
            numReviws:12,
            description:'high quality product',
            CountInStock:10,
        },
        {
            _id:'4',
            name:'Nike shirt',
            category:' shirts',
            image:'/images/image4.jpg',
            price:120,
            brand:'Nike',
            rating:5,
            numReviws:12,
            description:'high quality product',
            CountInStock:10,
        },
        {
            _id:'5',
            name:'Nike oversize shirt',
            category:'oversize shirts',
            image:'/images/image5.jpeg',
            price:120,
            brand:'Nike',
            rating:4,
            numReviws:12,
            description:'high quality product',
            CountInStock:10,
        },
        {
            _id:'6',
            name:'Nike slim shirt',
            category:'Slim shirts',
            image:'images/image6.jpg',
            price:120,
            brand:'Nike',
            rating:1,
            numReviws:12,
            description:'high quality product',
            CountInStock:10,
        }
    ]
};
export default data ;